# Generated by Django 6.0.4 on 2026-05-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField()),
                ('date', models.DateField()),
                ('party_size', models.IntegerField()),
                ('requested_time', models.TimeField()),
                ('time_delta_minutes', models.IntegerField(null=True)),
                ('booked_time', models.TimeField(null=True)),
                ('reservation_id', models.CharField(blank=True, max_length=128)),
                ('resy_token', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
